{"name": "test_create_auth_with_excel[user_cred2]", "status": "broken", "statusDetails": {"message": "KeyError: 'useername'", "trace": "user_cred = {'password': 'password125', 'username': 'admin562'}\n\n    @pytest.mark.parametrize(\"user_cred\", read_credentials_from_excel(os.getcwd() + \"/TestData_DDTesting.xlsx\"))\n    def test_create_auth_with_excel(user_cred):\n>       username = user_cred[\"useername\"]\nE       KeyError: 'useername'\n\nDDTesting_Better.py:38: KeyError"}, "parameters": [{"name": "user_cred", "value": "{'username': 'admin562', 'password': 'password125'}"}], "start": 1712654465019, "stop": 1712654465020, "uuid": "dfd2bada-3b66-4184-a893-dae1cd94ecf7", "historyId": "95f2e36bb2eca28a198eca1a044c96c3", "testCaseId": "f9a4cb542c5c0a69195291e9a6a82ff9", "fullName": "tests.test.DataDrivenTesting.DDTesting_Better#test_create_auth_with_excel", "labels": [{"name": "parentSuite", "value": "tests.test.DataDrivenTesting"}, {"name": "suite", "value": "DDTesting_Better"}, {"name": "host", "value": "LAPTOP-G6QKH92C"}, {"name": "thread", "value": "13948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.DataDrivenTesting.DDTesting_Better"}]}