{"name": "test_create_auth_with_excel[user_cred3]", "status": "broken", "statusDetails": {"message": "KeyError: 'useername'", "trace": "user_cred = {'password': 'password126', 'username': 'admi@hjk'}\n\n    @pytest.mark.parametrize(\"user_cred\", read_credentials_from_excel(os.getcwd() + \"/TestData_DDTesting.xlsx\"))\n    def test_create_auth_with_excel(user_cred):\n>       username = user_cred[\"useername\"]\nE       KeyError: 'useername'\n\nDDTesting_Better.py:38: KeyError"}, "parameters": [{"name": "user_cred", "value": "{'username': 'admi@hjk', 'password': 'password126'}"}], "start": 1712654465026, "stop": 1712654465026, "uuid": "06ef067c-e345-4c85-97b5-5bc69438e8f0", "historyId": "be9cf1e81f6dc49d6035a0f900496c22", "testCaseId": "f9a4cb542c5c0a69195291e9a6a82ff9", "fullName": "tests.test.DataDrivenTesting.DDTesting_Better#test_create_auth_with_excel", "labels": [{"name": "parentSuite", "value": "tests.test.DataDrivenTesting"}, {"name": "suite", "value": "DDTesting_Better"}, {"name": "host", "value": "LAPTOP-G6QKH92C"}, {"name": "thread", "value": "13948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.DataDrivenTesting.DDTesting_Better"}]}